language: generic
cache: apt
matrix:
  include:
    - compiler: nvcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - nvidia-cuda-dev nvidia-profiler nvidia-cuda-toolkit
      env: NVCC=nvcc
script:
  - make
  - make test
